BOARD_TAG = mega
BOARD_SUB = atmega2560
MONITOR_BAUDRATE=115200
ARDUINO_SKETCHBOOK = ../
ARDUINO_LIBS = Arduino_FreeRTOS_Library ucomm Wire I2Cdev MPU6050 TimerOne
include ../.Arduino-Makefile/Arduino.mk
